name: C_Lingo CI

on:
  push:
    branches: [ master, developer ]
  pull_request:
    branches: [ master, developer ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make test
      run: make test
#    - name: make distcheck
#      run: make distcheck
