name: C_Lingo CI

on:
  push:
    branches: [ master, developer ]
  pull_request:
    branches: [ master, developer ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make lingo_words
      run: make -C ./lingoWords
    - name: make tests
      run: make -C ./tests
      run: make run -C ./tests
    - name: make c_lingo
      run: make
