name: C_Lingo CI

on:
  push:
    branches: [ master, developer ]
  pull_request:
    branches: [ master, developer ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make lingo_words
      run: make -C ./lingoWords
    - name: make staticAnalysis
      run: cd ./tests/staticAnalysis && make && ./main && cd ../..
    - name: make tests
      run: cd ./tests && make && ./main --local && cd ..
    - name: make test_double
      run: cd ./tests/testDouble && make && ./main && cd ../..
    - name: make c_lingo
      run: make
